version: '3':
services:
  backend:
    restart: always
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - ./api:/app
      - uploads:/app/uploads
    entrypoint: /start-reload.sh

  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - 8804:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

